// *** image
import img1b from "../img/content-images/desktop-development-1.jpg";
import img1s from "../img/content-images/mobile-development-1.jpg";
import img2b from "../img/content-images/desktop-development-2.jpg";
import img2s from "../img/content-images/mobile-development-2.jpg";
import img3b from "../img/content-images/desktop-development-3.jpg";
import img3s from "../img/content-images/mobile-development-3.jpg";
import img4b from "../img/content-images/desktop-development-4.jpg";
import img4s from "../img/content-images/mobile-development-4.jpg";

export const MenuItem1 = [
  {
    title: "Hampton Manor",
    subtitle: "SPECIAL DEVELOPMENT",
    area: "Surrey",
    location: "Godalming, Surrey,",
    postcode: "GU7 2AS",
    info: "5 homes remaining from £745,000",
    house_path: "/",
    location_path: "/",
    imgB: img1b,
    imgS: img1s,
  },
  {
    title: "White Lion Place",
    subtitle: "ALMOST GONE",
    area: "Surrey",
    location: "Cobham, Surrey,",
    postcode: "KT11 1HY",
    info: "Only 1 home left!",
    house_path: "/",
    location_path: "/",
    imgB: img2b,
    imgS: img2s,
  },
  {
    title: "Orford Place",
    subtitle: "COMING SOON",
    area: "Surrey",
    location: "Ham Common, Richmond,",
    postcode: "TW10 7JH",
    info: "Launching April 2021",
    house_path: "/",
    location_path: "/",
    imgB: img3b,
    imgS: img3s,
  },
  {
    title: "The Farthings",
    subtitle: "AVAILABLE NOW",
    area: "Surrey",
    location: "Leatherhead, Surrey,",
    postcode: "KT22 7GP",
    info: "3 homes remaining from £840,000",
    house_path: "/",
    location_path: "/",
    imgB: img4b,
    imgS: img4s,
  },
  {
    title: "Hampton Manor",
    subtitle: "SPECIAL DEVELOPMENT",
    area: "Oxfordshire",
    location: "Godalming, Surrey,",
    postcode: "GU7 2AS",
    info: "5 homes remaining from £745,000",
    house_path: "/",
    location_path: "/",
    imgB: img1b,
    imgS: img1s,
  },
  {
    title: "White Lion Place",
    subtitle: "ALMOST GONE",
    area: "Hertfordshire",
    location: "Cobham, Surrey,",
    postcode: "KT11 1HY",
    info: "Only 1 home left!",
    house_path: "/",
    location_path: "/",
    imgB: img2b,
    imgS: img2s,
  },
  {
    title: "The Farthings",
    subtitle: "AVAILABLE NOW",
    area: "Hertfordshire",
    location: "Leatherhead, Surrey,",
    postcode: "KT22 7GP",
    info: "3 homes remaining from £840,000",
    house_path: "/",
    location_path: "/",
    imgB: img4b,
    imgS: img4s,
  },
  {
    title: "Orford Place",
    subtitle: "COMING SOON",
    area: "Berkshire",
    location: "Ham Common, Richmond,",
    postcode: "TW10 7JH",
    info: "Launching April 2021",
    house_path: "/",
    location_path: "/",
    imgB: img3b,
    imgS: img3s,
  },
  {
    title: "Hampton Manor",
    subtitle: "SPECIAL DEVELOPMENT",
    area: "Berkshire",
    location: "Godalming, Surrey,",
    postcode: "GU7 2AS",
    info: "5 homes remaining from £745,000",
    house_path: "/",
    location_path: "/",
    imgB: img1b,
    imgS: img1s,
  },
  {
    title: "The Farthings",
    subtitle: "AVAILABLE NOW",
    area: "Berkshire",
    location: "Leatherhead, Surrey,",
    postcode: "KT22 7GP",
    info: "3 homes remaining from £840,000",
    house_path: "/",
    location_path: "/",
    imgB: img4b,
    imgS: img4s,
  },
  {
    title: "The Farthings",
    subtitle: "AVAILABLE NOW",
    area: "Kent",
    location: "Leatherhead, Surrey,",
    postcode: "KT22 7GP",
    info: "3 homes remaining from £840,000",
    house_path: "/",
    location_path: "/",
    imgB: img4b,
    imgS: img4s,
  },
  {
    title: "Orford Place",
    subtitle: "COMING SOON",
    area: "Kent",
    location: "Ham Common, Richmond,",
    postcode: "TW10 7JH",
    info: "Launching April 2021",
    house_path: "/",
    location_path: "/",
    imgB: img3b,
    imgS: img3s,
  },
];
